DECLARE
  dept_id HR.DEPARTMENTS.DEPARTMENT_ID%TYPE;
  dept_name HR.DEPARTMENTS.DEPARTMENT_NAME%TYPE;
  
BEGIN
  SELECT DEPARTMENT_ID, DEPARTMENT_NAME
  INTO   dept_id, dept_name
  FROM HR.DEPARTMENTS
  WHERE DEPARTMENT_ID = 60;
  
  IF SQL%FOUND THEN
    dbms_output.put_line(SQL%ROWCOUNT);
  END IF;
END;